<div class="sources">
    <ul>
        <ul>
            <li>https://laravel.com/docs/10.x</li>
            <li>https://laravel.com/docs/10.x/authentication</li>
            <li>https://laravel.com/docs/10.x/blade</li>
            <li>https://laravel.com/docs/10.x/configuration</li>
            <li>https://laravel.com/docs/10.x/controllers</li>
            <li>https://laravel.com/docs/10.x/csrf</li>
            <li>https://laravel.com/docs/10.x/database</li>
            <li>https://laravel.com/docs/10.x/eloquent</li>
            <li>https://laravel.com/docs/10.x/filesystem</li>
            <li>https://laravel.com/docs/10.x/installation</li>
            <li>https://laravel.com/docs/10.x/lifecycle</li>
            <li>https://laravel.com/docs/10.x/mail</li>
            <li>https://laravel.com/docs/10.x/middleware</li>
            <li>https://laravel.com/docs/10.x/migrations</li>
            <li>https://laravel.com/docs/10.x/notifications</li>
            <li>https://laravel.com/docs/10.x/passport</li>
            <li>https://laravel.com/docs/10.x/passwords</li>
            <li>https://laravel.com/docs/10.x/queries</li>
            <li>https://laravel.com/docs/10.x/readme</li>
            <li>https://laravel.com/docs/10.x/requests</li>
            <li>https://laravel.com/docs/10.x/routing</li>
            <li>https://laravel.com/docs/10.x/seeding</li>
            <li>https://laravel.com/docs/10.x/starter-kits</li>
            <li>https://laravel.com/docs/10.x/structure</li>
            <li>https://laravel.com/docs/10.x/telescope</li>
            <li>https://laravel.com/docs/10.x/upgrade</li>
            <li>https://laravel.com/docs/10.x/urls</li>
            <li>https://laravel.com/docs/10.x/validation</li>
            <li>https://laravel.com/docs/4.2/migrations</li>
            <li>https://laravel.com/docs/4.2/quick</li>
            <li>https://laravel.com/docs/5.5/requests</li>
            <li>https://laravel.com/docs/7.x/eloquent</li>
            <li>https://laravel.com/docs/8.x/eloquent</li>
            <li>https://laravel.com/docs/8.x/installation</li>
            <li>https://laravel.com/docs/8.x/upgrade</li>
            <li>https://laravel.com/docs/9.x/helpers</li>
            <li>https://laravel.com/docs/9.x/sail</li>
            <li>https://laravel.com/docs/9.x/upgrade</li>
            <li>https://nova.laravel.com/</li>
        </ul>
        <ul>
            <li>https://stackoverflow.com/questions/22943570/laravel-method-show-does-not-exist</li>
            <li>https://stackoverflow.com/questions/24744825/access-query-string-values-from-laravel</li>
            <li>https://stackoverflow.com/questions/25329302/laravel-error-pdoexception-could-not-find-driver-in-postgresql</li>
            <li>https://stackoverflow.com/questions/25849015/laravel-eloquent-where-not-in</li>
            <li>https://stackoverflow.com/questions/26973442/laravel-blade-check-box</li>
            <li>https://stackoverflow.com/questions/28714675/laravel-says-route-not-defined</li>
            <li>https://stackoverflow.com/questions/29115385/how-to-make-laravel-eloquent-in-query</li>
            <li>https://stackoverflow.com/questions/34852906/how-to-get-real-time-updates-in-a-laravel-app</li>
            <li>https://stackoverflow.com/questions/35111806/laravel-5-postgresql-database-postgres-not-configured-error</li>
            <li>https://stackoverflow.com/questions/35753951/manually-register-a-user-in-laravel</li>
            <li>https://stackoverflow.com/questions/40870385/how-to-changed-default-path-public-name-in-laravel</li>
            <li>https://stackoverflow.com/questions/41092490/undefined-constant-app-http-controllers-app-classname-laravel</li>
            <li>https://stackoverflow.com/questions/41928237/laravel-sqlstate3f000-invalid-schema-name</li>
            <li>https://stackoverflow.com/questions/41981123/laravel-loop-in-form</li>
            <li>https://stackoverflow.com/questions/44653359/laravel-method-where-does-not-exist-error</li>
            <li>https://stackoverflow.com/questions/48190672/how-do-i-use-partials-in-laravel-5</li>
            <li>https://stackoverflow.com/questions/50445945/laravel-redirect-with-variable-and-display-it-in-the-view-file</li>
            <li>https://stackoverflow.com/questions/52056782/routes-laravel-with-a-variable</li>
            <li>https://stackoverflow.com/questions/52583886/post-request-in-laravel-error-419-sorry-your-session-419-your-page-has-exp</li>
            <li>https://stackoverflow.com/questions/53960792/laravel-2-forms-on-the-same-page-url-posting-to-individual-routes</li>
            <li>https://stackoverflow.com/questions/55334032/laravel-guest-middleware</li>
            <li>https://stackoverflow.com/questions/62063569/method-create-not-found-in-app-user-laravel-7</li>
            <li>https://stackoverflow.com/questions/63921151/laravel-guest-middleware-do-not-redirect-properly</li>
            <li>https://stackoverflow.com/questions/68432161/the-image-must-be-an-image-laravel-validation-error</li>
            <li>https://stackoverflow.com/questions/73035709/laravel-9-how-to-prevent-showing-login-page-after-user-is-logged-in-and-hit-br</li>
            <li>https://stackoverflow.com/questions/74939264/i-cant-get-authuser-in-laravel</li>
            <li>https://stackoverflow.com/questions/76537955/how-to-resolve-cors-issue-in-laravel-version-10</li>
        </ul>
        <ul>
            <li>https://laracasts.com/discuss/channels/laravel/column-doesnt-exists-it-does</li>
            <li>https://laracasts.com/discuss/channels/laravel/create-method-does-not-exist-error-even-its-on-the-controller</li>
            <li>https://laracasts.com/discuss/channels/laravel/guest-middleware-not-working</li>
            <li>https://laracasts.com/discuss/channels/laravel/migrating-database</li>
            <li>https://laracasts.com/discuss/channels/laravel/not-working-laravel-seed</li>
            <li>https://laracasts.com/discuss/channels/laravel/retreiving-logged-in-user-id-from-session-laravel-6</li>
        </ul>
        <ul>
            <li>https://benjamincrozat.com/check-laravel-version</li>
            <li>https://fly.io/docs/laravel/database-guides/laravel-pgsql/</li>
            <li>https://redberry.international/laravel-route-group-organize-your-code/</li>
            <li>https://medium.com/@misteryomi/how-to-live-reload-your-laravel-application-68c12f16779b</li>
            <li>https://tonyfrenzy.medium.com/using-postgresql-with-laravel-c4c320ca7f34</li>
            <li>https://www.cloudways.com/blog/setup-laravel-login-authentication/</li>
            <li>https://www.enterprisedb.com/postgres-tutorials/how-use-postgresql-laravel</li>
            <li>https://www.reddit.com/r/neovim/comments/146802p/neovim_and_laravelphp/</li>
        </ul>
    </ul>
</div>
